package oem.edge.ed.odc.dsmp.common;

import java.awt.Event;

/**
 * An base event class generated by a Dispatcher in response to protocol received
 * from the a server. See the is*() methods in subclasses for definition of valid properties
 * set for specific event types.
 *
 * @version 1.0.0.0 02/21/2003
 * @author Mike Zarnick
 */
public class DSMPEvent {
	/**
	 * Event identifier. See static properties of subclasses for possible values.
	 **/
	public int reason;
	/**
	 * Flags. 8 individual flags. See subclass is*() methods for possible settings
	 */
	public byte flags;
	/*
	 * Request identifier. Used by the application to aide correlation of a reply to a specific request.
	 */
	public byte handle;
/**
 * DBEvent constructor for basic events.
 * <p>This constructor is not normally called directly. Those interested in receiving these events
 * should register as an EventListener with an appropriate Dispatcher instead. See subclasses.</p>
 * @param reason int
 * @param flags byte
 * @param handle byte
 *
 * @see #reason
 * @see #flags
 * @see #handle
 */
public DSMPEvent(int reason,byte flags,byte handle) {
	this.reason = reason;
	this.flags = flags;
	this.handle = handle;
}
}
